resourcepack:
  url: https://raw.githubusercontent.com/Valgrifer/LoupGarou/master/resourcepack/loup_garou.zip
  useResourcePackHosting: false
  generateResourcePack: false
  path: ./resourcepack/loup_garou.zip
compo:
  hidden: false
  update_on_kill: true
